spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopwise_db?useSSL=false&serverTimezone=UTC
    username: root
    password: Suren@66
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

application:
  security:
    jwt:
      secret-key: y7P5ea+q6HIYQk+qlyxDNCKBnHKSxtC6UFDG7RENrsTCfGXmT1HziodBgOaKRwFZmAslieayLyQUoInp4Fx3CA==
      expiration: 86400000 # 1 day
      refresh-token:
        expiration: 604800000 # 7 days

app:
  client:
    url: http://localhost:4200/login

server:
  port: 8086